---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "CS6101 - Deep Unsupervised Learning"
keywords:    "CS6101, Deep Learning, Unsupervised Learning, NUS"
description: "This is a section of the CS 6101 Exploration of Computer Science Research at NUS. CS 6101 is a 4 modular credit pass/fail module for new incoming graduate programme students to obtain background in an area with an instructor's support. It is designed as a lab rotation to familiarize students with the methods and ways of research in a particular research area.  This semester's them will be on Deep Unsupervised Learning."
source_link: "http://www.comp.nus.edu.sg/~kanmy/courses/6101_1910"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: "UA-9594235-3"

### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  #maritimo
  color1: '#162D59'
  color2: '#5679A6'
  color3: '#F2D5A0'
  color4: '#D98014'
  color5: '#735236'

kramdown:
  auto_ids:  false

